package constants;

import settings.EvoTypes;

public enum Cards {
	
        //Grass
	Bulbasaur (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.BulbaIvyVenusaur.ordinal()),
	Ivysaur (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.BulbaIvyVenusaur.ordinal()),
	Venusaur1 (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.BulbaIvyVenusaur.ordinal()),
	Venusaur2 (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.BulbaIvyVenusaur.ordinal()),
        
	Caterpie (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.CatMetaFree.ordinal()),
	Metapod (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.CatMetaFree.ordinal()),
	Butterfree (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistFight.ordinal(),
            WRGroups.WRGroupsByLine.CatMetaFree.ordinal()),
        
	Weedle (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.WeeKaBee.ordinal()),
	Kakuna (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.WeeKaBee.ordinal()),
	Beedrill (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistFight.ordinal(),
            WRGroups.WRGroupsByLine.WeeKaBee.ordinal()),
        
	Ekans (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.EkArbok.ordinal()),
	Arbok (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.EkArbok.ordinal()),
        
	NidoranF (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.NidoFRinaQueen.ordinal()),
	Nidorina (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.NidoFRinaQueen.ordinal()),
	Nidoqueen (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.NidoFRinaQueen.ordinal()),
        
	NidoranM (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.NidoMRinoKing.ordinal()),
	Nidorino (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.NidoMRinoKing.ordinal()),
	Nidoking (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.NidoMRinoKing.ordinal()),
        
	Zubat (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistFight.ordinal(),
            WRGroups.WRGroupsByLine.ZuGolbat.ordinal()),
	Golbat (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistFight.ordinal(),
            WRGroups.WRGroupsByLine.ZuGolbat.ordinal()),
        
	Oddish (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.OddGloomVile.ordinal()),
	Gloom (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.OddGloomVile.ordinal()),
	Vileplume (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.OddGloomVile.ordinal()),
        
	Paras (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.ParaParasect.ordinal()),
	Parasect (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.ParaParasect.ordinal()),
        
	Venonat (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.NatMoth.ordinal()),
	Venomoth (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistFight.ordinal(),
            WRGroups.WRGroupsByLine.NatMoth.ordinal()),
        
	Bellsprout (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.BellWepVic.ordinal()),
	Weepinbell (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.BellWepVic.ordinal()),
	Victreebel (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.BellWepVic.ordinal()),
        
	Grimer (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GrimerMuk.ordinal()),
	Muk (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GrimerMuk.ordinal()),
        
	Exeggcute (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Exegg.ordinal()),
	Exeggutor (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Exegg.ordinal()),
        
	Koffing (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.KoffWeez.ordinal()),
	Weezing (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.KoffWeez.ordinal()),
        
	Tangela1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Tangela.ordinal()),
	Tangela2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Tangela.ordinal()),
        
	Scyther (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Scyther.ordinal()),
        
	Pinsir (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFireResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Pinsir.ordinal()),
        
        //Fire
	Charmander (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.CharmanLeonZard.ordinal()),
	Charmeleon (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.CharmanLeonZard.ordinal()),
	Charizard (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistFight.ordinal(),
            WRGroups.WRGroupsByLine.CharmanLeonZard.ordinal()),
            
	Vulpix (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.VulpNine.ordinal()),
	Ninetails1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.VulpNine.ordinal()),
	Ninetails2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.VulpNine.ordinal()),
        
	Growlithe (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GrowlNine.ordinal()),
	Arcanine1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GrowlNine.ordinal()),
	Arcanine2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GrowlNine.ordinal()),
        
	Ponyta (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PonyDash.ordinal()),
	Rapidash (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PonyDash.ordinal()),
        
	Magmar1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Magmar.ordinal()),
	Magmar2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Magmar.ordinal()),
        
	Flareon1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Eevee.ordinal()),
	Flareon2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakWaterResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Eevee.ordinal()),
        
	Moltres1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Moltres.ordinal()),
	Moltres2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Moltres.ordinal()),
        
        //Water
	Squirtle (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SqirWarBlastoise.ordinal()),
	Wartortle (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SqirWarBlastoise.ordinal()),
	Blastoise (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SqirWarBlastoise.ordinal()),
        
	Psyduck (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PsyGolduck.ordinal()),
	Golduck (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PsyGolduck.ordinal()),
        
	Poliwag (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PoliwagWhirlWrath.ordinal()),
	Poliwhirl (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PoliwagWhirlWrath.ordinal()),
	Poliwrath (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PoliwagWhirlWrath.ordinal()),
        
	Tentacool (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.TentaCC.ordinal()),
	Tentacruel (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.TentaCC.ordinal()),
        
	Seel (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SeeDewgong.ordinal()),
	Dewgong (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SeeDewgong.ordinal()),
        
	Shellder (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.ShellCloyster.ordinal()),
	Cloyster (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.ShellCloyster.ordinal()),
        
	Krabby (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.KrabKing.ordinal()),
	Kingler (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.KrabKing.ordinal()),
        
	Horsea (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.HorseaDra.ordinal()),
	Seadra (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.HorseaDra.ordinal()),
        
	Goldeen (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GoldKing.ordinal()),
	Seaking (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GoldKing.ordinal()),
        
	Staryu (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.StaryuMie.ordinal()),
	Starmie (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.StaryuMie.ordinal()),
        
	Magikarp (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MagiDos.ordinal()),
	Gyarados (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistFight.ordinal(),
            WRGroups.WRGroupsByLine.MagiDos.ordinal()),
        
	Lapras (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Lapras.ordinal()),
        
	Vaporeon1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Eevee.ordinal()),
	Vaporeon2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Eevee.ordinal()),
        
	Omanyte (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.OmanyteStar.ordinal()),
	Omastar (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.OmanyteStar.ordinal()),
        
	Articuno1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Articuno.ordinal()),
	Articuno2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Articuno.ordinal()),
        
        //Lightning
	Pikachu1 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	Pikachu2 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	Pikachu3 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	Pikachu4 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	FlyingPikachu (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	SurfingPikachu1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	SurfingPikachu2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	Raichu1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
	Raichu2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.PikaRaichu.ordinal()),
        
	Magnemite1 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MagnemiteTon.ordinal()),
	Magnemite2 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MagnemiteTon.ordinal()),
	Magneton1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MagnemiteTon.ordinal()),
	Magneton2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MagnemiteTon.ordinal()),
        
	Voltorb (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.VoltTrode.ordinal()),
	Electrode1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.VoltTrode.ordinal()),
	Electrode2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.VoltTrode.ordinal()),
        
	Electabuzz1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Electabuzz.ordinal()),
	Electabuzz2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Electabuzz.ordinal()),
        
	Jolteon1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Eevee.ordinal()),
	Jolteon2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Eevee.ordinal()),
        
	Zapdos1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Zapdos.ordinal()),
	Zapdos2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Zapdos.ordinal()),
	Zapdos3 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Zapdos.ordinal()),
        
        //Fighting
	Sandshrew (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.ShrewSlash.ordinal()),
	Sandslash (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.ShrewSlash.ordinal()),
        
	Diglett (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.DigTrio.ordinal()),
	Dugtrio (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.DigTrio.ordinal()),
        
	Mankey (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MankApe.ordinal()),
	Primeape (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MankApe.ordinal()),
        
	Machop (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.ChopChokeChamp.ordinal()),
	Machoke (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.ChopChokeChamp.ordinal()),
	Machamp (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.ChopChokeChamp.ordinal()),
        
	Geodude (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GeoGravGolem.ordinal()),
	Graveler (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GeoGravGolem.ordinal()),
	Golem (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.GeoGravGolem.ordinal()),
        
	Onix (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Onix.ordinal()),
	
        Cubone (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.CueWak.ordinal()),
	Marowak1 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.CueWak.ordinal()),
	Marowak2 (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.CueWak.ordinal()),
        
	Hitmonlee (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Hitmonlee.ordinal()),
        
	Hitmonchan (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Hitmonchan.ordinal()),
        
	Rhyhorn (EvoTypes.EVO1OF2.ordinal(),
                WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
                WRGroups.WRGroupsByLine.HornDon.ordinal()),
	Rhydon (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistLight.ordinal(),
            WRGroups.WRGroupsByLine.HornDon.ordinal()),
        
	Kabuto (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.KabutoTops.ordinal()),
	Kabutops (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistNone.ordinal(),
            WRGroups.WRGroupsByLine.KabutoTops.ordinal()),
        
	Aerodactyl (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakGrassResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Aerodactyl.ordinal()),
        
        //Psychic
	Abra (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.AbKabZam.ordinal()),
	Kadabra (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.AbKabZam.ordinal()),
	Alakazam (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.AbKabZam.ordinal()),
        
	Slowpoke1 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SlopokeBro.ordinal()),
	Slowpoke2 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SlopokeBro.ordinal()),
	Slowbro (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.SlopokeBro.ordinal()),
        
	Gastly1 (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.GasHauntGengar.ordinal()),
	Gastly2 (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.GasHauntGengar.ordinal()),
	Haunter1 (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.GasHauntGengar.ordinal()),
	Haunter2 (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.GasHauntGengar.ordinal()),
	Gengar (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.GasHauntGengar.ordinal()),
        
	Drowzee (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.DrowzeeNo.ordinal()),
	Hypno (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.DrowzeeNo.ordinal()),
        
	MrMime (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.MrMime.ordinal()),
        
	Jynx (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Jynx.ordinal()),
        
	Mewtwo1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Mewtwo.ordinal()),
	Mewtwo2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Mewtwo.ordinal()),
	Mewtwo3 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Mewtwo.ordinal()),
        
	Mew1 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Mew.ordinal()),
	Mew2 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Mew.ordinal()),
	Mew3 (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakPsyResistNone.ordinal(),
            WRGroups.WRGroupsByLine.Mew.ordinal()),
        
        //Colorless
	Pidgey (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.PidgeyOttoOt.ordinal()),
	Pidgeotto (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.PidgeyOttoOt.ordinal()),
	Pidgeot1 (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.PidgeyOttoOt.ordinal()),
	Pidgeot2 (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.PidgeyOttoOt.ordinal()),
        
	Rattata (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.RattIcate.ordinal()),
	Raticate (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.RattIcate.ordinal()),
        
	Spearow (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.SpFearow.ordinal()),
	Fearow (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.SpFearow.ordinal()),
        
	Clefairy (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.ClefairAble.ordinal()),
	Clefable (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.ClefairAble.ordinal()),
        
	Jigglypuff1 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.JigglyTuff.ordinal()),
	Jigglypuff2 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.JigglyTuff.ordinal()),
	Jigglypuff3 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.JigglyTuff.ordinal()),
	Wigglytuff (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.JigglyTuff.ordinal()),
        
	Meowth1 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.MeowSian.ordinal()),
	Meowth2 (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.MeowSian.ordinal()),
	Persian (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.MeowSian.ordinal()),
        
	Farfetchd (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.Farfetchd.ordinal()),
        
	Doduo (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.DoduoDrio.ordinal()),
	Dodrio (EvoTypes.EVO2OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakLightResistFight.ordinal(),
            WRGroups.WRGroupsByLine.DoduoDrio.ordinal()),
        
	Lickitung (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Lickitung.ordinal()),
        
	Chansey (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Chansey.ordinal()),
        
	Kangaskhan (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Kangaskhan.ordinal()),
        
	Tauros (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Tauros.ordinal()),
        
	Ditto (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Ditto.ordinal()),
        
	Eevee (EvoTypes.EVO1OF2.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Eevee.ordinal()),
        
	Porygon (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Porygon.ordinal()),
        
	Snorlax (EvoTypes.EVO1OF1.ordinal(),
            WRGroups.WRGroupsByComb.WeakFightResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.Snorlax.ordinal()),
        
	Dratini (EvoTypes.EVO1OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.DratAirIte.ordinal()),
	Dragonair (EvoTypes.EVO2OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistPsy.ordinal(),
            WRGroups.WRGroupsByLine.DratAirIte.ordinal()),
	Dragonite1 (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.DratAirIte.ordinal()),
	Dragonite2 (EvoTypes.EVO3OF3.ordinal(),
            WRGroups.WRGroupsByComb.WeakNoneResistFight.ordinal(),
            WRGroups.WRGroupsByLine.DratAirIte.ordinal());
	
	private final int evoType; //Indicates current stage and maximum form
        private final int wrComb; //Indicates the weakness/resisistance combination
        private final int wrLine; //Indicates the family of cards the card belongs to
	
	Cards (int evoType, int wrComb, int wrLine) {
		this.evoType = evoType;
                this.wrComb = wrComb;
                this.wrLine = wrLine;
	}
        
        /* Returns the stage of the card within its line. See EvoTypes enum.*/
	public int getEvoType() {
		return evoType;
	}
        
        /** Returns the weakness/resistance combination of the original card. See
            WRGroupsByComb enum.*/
        public int getWRComb() {
		return wrComb;
	}
        
        /** Returns the weakness/resistance evolution line of the original card. 
            See WRGroupsByLine enum.*/
        public int getWRLine() {
		return wrLine;
	}
        
        /** Returns whether the passed in card is considered an "illusion" card
            (one normally obtainable only via Card Pop!). These are Venusaur Lv.
            64 and Mew Lv. 15. */
        public static boolean isIllusionCard(int cardIndex) {
            if (cardIndex == Cards.Venusaur1.ordinal() || cardIndex == Cards.Mew2.ordinal())
            {
                return true;
            }
            return false;
        }

}
